"""Task domain model."""

from pydantic import BaseModel, Field
from typing import Literal

class Task(BaseModel):
    """Represents a discrete unit of work generated by an agent."""
    title: str = Field(..., description="The title of the task")
    description: str = Field(..., description="Detailed description of what needs to be done")
    assignee_role: Literal["CTO", "PM", "CFO", "Investor"] = Field(..., description="The role assigned to complete this task")
    status: Literal["pending", "in_progress", "completed"] = Field("pending", description="Current status of the task")
